/**
 * Human-facing UI copy.
 *
 * Prompt text that is sent to Pi stays in English inside the context builder,
 * the bundled instructions, and the runtime diagnostics: translating those
 * changes instruction following, breaks the documented `/context show` field
 * values, and raises the token cost of every request.
 */
export const STRINGS = {
  common: {
    apply: "应用",
    back: "返回",
    cancel: "取消",
    close: "关闭",
    copiedToClipboard: "已复制到剪贴板。",
    delete: "删除",
    reject: "拒绝",
    rename: "重命名",
    save: "保存"
  },
  view: {
    attachFiles: "添加附件",
    canceling: "正在取消",
    chatTitle: "会话标题",
    contextUsageEmpty: "上下文 --",
    markdownRenderError: "Pi Agent：Markdown 渲染出错",
    modelProvider: "模型提供商",
    renameChat: "重命名会话",
    chooseAttachable: "选择库中的图片、文本、代码或配置文件…",
    collectingContext: "收集当前笔记、链接、反向链接与显式附件。",
    compactionUnknownTitle:
      "Pi 已压缩本次会话。在下一次模型回复返回新的 token 用量前，无法得知确切的上下文占用。",
    compactionBadge: (contextWindow) => `上下文已压缩 · ?/${contextWindow}`,
    contextUsagePending: "上下文占用会在 Pi 返回所选模型的 token 用量后显示。",
    contextUsagePendingTitle: "上下文占用会在 Pi 返回所选模型的 token 用量后显示。",
    forkBusy: "请先等当前会话的智能体运行结束，再派生该会话。",
    forkChat: "派生会话",
    inputPlaceholder: "向智能体询问你的库… Enter 发送，Shift+Enter 换行。",
    localFile: "本地文件",
    manageThreads: "管理会话",
    modelNoImage: "所选 Pi 模型不支持图片输入。",
    newChat: "新建会话",
    pendingContext: "本次将附带的上下文",
    preparingContext: "正在准备上下文",
    queuedEmpty: "排队中的消息已为空，未发送。",
    runCanceled: "已取消运行。",
    runFailed: "运行失败",
    send: "发送",
    sendMessage: "发送消息",
    threadNotFound: "会话不存在。",
    vaultFile: "库文件",
    annotationsCount: (count) => `${count} 条注解`,
    clearAnnotations: (count) => `清除 ${count} 条注解`,
    notificationCompleted: "智能体回复完成。点击打开会话。",
    notificationFailed: "智能体运行失败。点击打开会话。",
    removeNote: (name) => `移除「${name}」`,
    removePending: (name) => `移除「${name}」`
  },
  sendState: {
    cancel: "取消",
    cancelAria: "取消智能体运行",
    canceling: "取消中",
    cancelingAria: "正在取消智能体运行",
    queue: "排队",
    queueAria: "把消息加入队列",
    queuedSuffix: (count) => `已排队 ${count} 条。`
  },
  controls: {
    mode: "模式",
    model: "模型",
    noModels: "没有可用的模型",
    think: "思考",
    label: (name, value) => `${name}：${value}`
  },
  queue: {
    discard: "全部丢弃",
    discardSaved: "丢弃全部已保存的消息",
    editQueued: "编辑排队消息",
    queuedNotice: (count) =>
      count === 1 ? "消息已排队，将在当前运行结束后发送。" : `${count} 条消息已排队。`,
    removeQueued: "移除排队消息",
    settledNotice: "本次运行已结束，消息将正常发送。",
    steerNow: "立即插队",
    unknownSize: "大小未知",
    handedToPi: "已交给 Pi",
    resume: "继续",
    resumeSaved: "继续发送已保存的消息",
    runsAfterSettlement: "当前运行结束后会按顺序发送。",
    savedFromPreviousSession: "来自上一次插件会话，发送前请确认。",
    steeringSent: "已向 Pi 发送插队消息。",
    queuedImage: "排队图片",
    attachmentCount: (count) => `${count} 个附件`,
    followUpCount: (count) => `${count} 条本地排队消息`,
    queuedFollowUp: (label) => `排队消息：${label}`,
    attachmentSummary: (name, type, size, truncated) =>
      `${name} · ${type} · ${size}${truncated ? " · 已截断" : ""}`,
    imageSummary: (name, size) => `${name} · ${size} · 图片`
  },
  threads: {
    activeRunDeleteBlocked: "请先等智能体运行结束，再删除该会话。",
    agentRunningInChat: "该会话的智能体正在运行",
    backToChat: "返回对话",
    bulkCreatedEmpty: "已创建新的空会话",
    bulkSessionsKept: "本地 Pi 会话文件已保留。",
    chatTitle: "会话标题",
    currentChat: "当前会话",
    deletedChat: "会话已删除。",
    deletedChatAndSession: "会话与本地 Pi 会话已删除。",
    deleteBlockedByActiveRuns: "请先等待运行中的智能体结束后再删除会话。",
    exportFailed: "会话导出失败。",
    noSessionInfo: "没有可用的 Pi 会话信息。",
    nothingToDelete: "没有可删除的会话。",
    open: "打开",
    openChat: "打开会话",
    unknownDate: "未知日期",
    bulkDeleted: (count) => `已删除 ${count} 个会话`,
    bulkSkipped: (count) => `跳过 ${count} 个运行中的会话`,
    exportTo: (path) => `已导出到 ${path}`,
    messageCount: (count) => `${count} 条消息`,
    sessionStats: (file, messages, entries, tokens, cost) =>
      `${file}\n${messages} 条消息 · ${entries} 个树节点 · ${tokens} tokens · $${cost}`,
    updatedAt: (date) => `更新于 ${date}`,
    currentPrefix: "当前",
    deleteChat: "删除会话",
    deleteChats: "删除会话",
    deleteFailed: "无法删除该会话或其本地 Pi 会话文件。",
    empty: "暂无会话。",
    favorite: "收藏",
    heading: "会话",
    markFavorite: "收藏会话",
    removeFavorite: "取消收藏",
    newChat: "新建会话",
    nothingToFork: "暂无可派生的内容。",
    rowActions: "会话操作",
    threadNotFound: "会话不存在。",
    count: (count) => `${count} 个会话`,
    exportSession: (name) => `将 ${name} 会话导出为 HTML`,
    sessionInfo: (name) => `${name} 会话信息`
  },
  messages: {
    copied: "已复制回复。",
    copyResponse: "复制回复",
    createNote: "由回复创建笔记",
    editAndResend: "编辑并重发",
    insertIntoNote: "插入当前笔记",
    messageActions: "消息操作",
    noVaultLinks: "未找到库内链接。",
    openCitedNotes: "打开引用的笔记",
    openNoteFirst: "请先打开一篇笔记。",
    regenerate: "重新生成",
    responding: "回复中",
    responseTitle: "智能体回复",
    roleAgent: "智能体",
    roleYou: "你",
    searchVault: "在库中搜索相关内容",
    noteNotFound: (label) => `找不到笔记：${label}`
  },
  activity: {
    compactedRetrying: "已压缩上下文，正在重试",
    command: "命令",
    loadingSkillInstructions: "正在加载技能说明",
    thinking: "思考",
    usingSkillInstructions: "正在使用技能说明",
    compactingContext: "正在压缩上下文",
    compactionFailed: "压缩失败",
    compactionSkipped: "已跳过压缩",
    editing: "编辑",
    extensionFailed: "扩展失败",
    extensionError: "Pi 扩展错误",
    tool: "工具",
    finding: "查找",
    finishing: "收尾",
    listing: "列出",
    preparingAction: "准备操作",
    preparingCommand: "准备命令",
    preparingEdit: "准备编辑",
    preparingRead: "准备读取",
    preparingSearch: "准备搜索",
    preparingWrite: "准备写入",
    reading: "读取",
    retrying: "重试",
    running: "运行",
    searching: "搜索",
    startingPi: "启动 Pi",
    using: "使用",
    writing: "写入",
    inProgress: (label) => `正在${label}`,
    skill: (name) => `技能 · ${name}`,
    toolFailed: (name, detail) => (detail ? `${name}：${detail}` : `${name} 失败`),
    reviewingResults: "正在查看结果",
    toolFailedLabel: "工具执行失败"
  },
  modals: {
    before: "修改前",
    after: "修改后",
    applyChange: "应用修改",
    confirm: "确认",
    deleteChatOnly: "仅删除会话",
    deleteChatAndSession: "删除会话与本地 Pi 会话",
    deleteChatTitle: "删除会话？",
    deleteChatsDescription: "选择要删除哪些会话历史。本地 Pi 会话文件会保留。",
    deleteChatsTitle: "删除会话？",
    extensionFallback: "Pi 扩展",
    deleteAllChats: (count) => `删除全部会话（${count}）`,
    deleteAllExceptFavorites: (count) => `删除除收藏外的全部会话（${count}）`,
    approveChange: "批准库内修改",
    copyDiagnostics: "复制诊断命令",
    copyInstall: "复制安装命令",
    copiedDiagnostics: "已复制诊断命令。",
    copiedInstall: "已复制 Pi 安装命令。",
    fileChanged: "Pi 准备该修改后，文件已发生变化。",
    newFile: "（新文件）",
    doNotShowAgain: "不再显示",
    select: "选择",
    setupHeading: "设置 Pi CLI",
    setupIntro: "先在对话或审阅模式下使用。仅在你愿意让 Pi 修改的库中启用编辑或完整智能体模式。",
    setupMissingCli: "Pi Agent 需要先安装 Pi CLI 才能发送请求。",
    setupNodeHint:
      "安装 Node.js，或让你的 Node 版本管理器对 GUI 应用可见，然后完全重启 Obsidian。之后在终端运行 pi --version 确认 Pi 仍可用。",
    setupPathHint: "在终端安装 Pi 并在需要时完成认证，然后重启 Obsidian 以便读取更新后的 PATH。",
    favoriteProtected: (count) => `${count} 个收藏会话受第一个选项保护。`,
    activeRunBlocked: (count) => `${count} 个运行中的会话需等运行结束后才能删除。`,
    deleteChatQuestion: (title) => `要从插件历史中删除「${title}」吗？`,
    deleteChatOrSessionQuestion: (title) => `选择保留还是删除「${title}」的本地 Pi 会话。`
  },
  annotations: {
    change: "修改",
    question: "提问",
    intent: "注解意图",
    request: "请求内容",
    requestRequired: "请填写请求内容。",
    action: "添加或切换注解",
    addTitle: "添加注解",
    editTitle: "编辑注解",
    placeholder: "描述你的修改要求或问题",
    saveFailed: "无法保存注解。",
    pickModeHint: "注解拾取模式：悬停或聚焦某个段落，然后点击或按 Enter。",
    annotateBlock: "为该 Markdown 块添加注解",
    navigate: "跳转到注解",
    edit: "编辑注解",
    delete: "删除注解",
    noContext: "无上下文",
    renderedBlockGone: "该渲染块已不再对应当前笔记。",
    pickRenderedBlock: "请选择一个非空的渲染 Markdown 块。",
    renderedBlockTooLarge: "该渲染 Markdown 块过大，无法添加注解。",
    renderedSelectionLabel: "渲染选区（锚定到所属源块）",
    renderedSelectionNotMappable: "该渲染选区无法精确映射，将使用所属源块作为锚点。",
    storageInvalid: "注解数据无效。",
    storageDuplicateId: "注解 ID 已存在。",
    storageInvalidUpdate: "注解更新无效。",
    storageLimitReached: "注解存储已达上限。",
    blockAnchor: "块锚点",
    detached: "该注解已与当前笔记文本脱节。",
    listHeading: (count) => `注解（${count}）`,
    listTitle: "本文注解",
    notRendered: "该注解对应的源块当前未渲染。",
    send: "发送给 Pi",
    sendAria: "将注解发送给 Pi",
    sourceNotReady: "Markdown 编辑器尚未就绪。",
    openMarkdownFirst: "请先打开一篇 Markdown 笔记再使用注解。",
    selectionTooLarge: "所选 Markdown 文本过大，无法添加注解。",
    noSourceBlocks: "该阅读视图中没有可用的、能对应到源文件的 Markdown 块。",
    pickNonEmptyLine: "请选择一个非空的 Markdown 行或段落。",
    blockTooLarge: "该 Markdown 块过大，无法添加注解。",
    selectionAcrossBlocks: "请把选区限制在同一段可对应到源文件的 Markdown 文本内。",
    pickNonEmptyRendered: "请选择一个非空的渲染选区。",
    renderedSelectionGone: "该渲染选区已不属于当前 Markdown 视图。",
    renderedSelectionTooLarge: "渲染选区过大，无法添加注解。",
    mapFailed: "无法把该渲染选区映射到精确的源字符。",
    readSourceFailed: "无法读取当前 Markdown 源文本。",
    renderedTargetGone: "该渲染目标已不属于当前 Markdown 视图。"
  },
  suggestions: {
    folder: "文件夹",
    note: "笔记",
    tag: "标签",
    skill: (detail) => `技能 — ${detail}`
  },
  commands: {
    backlinksDetail: "附加链接到当前笔记的笔记。",
    backlinksLabel: "反向链接",
    compactDetail: "请求 Pi 压缩当前会话上下文，可附加自定义说明。",
    compactLabel: "压缩 Pi 上下文",
    contextShowDetail: "不调用 Pi，直接显示当前 Obsidian 上下文包。",
    contextShowHeading: "当前 Obsidian 上下文：",
    contextShowLabel: "显示上下文",
    currentDetail: "附加当前笔记、选区、链接、标签、标题与 frontmatter。",
    currentLabel: "当前笔记",
    linksDetail: "附加当前笔记链接出去的笔记。",
    linksLabel: "出链",
    searchDetail: "附加按相关度排序的库内笔记匹配结果。",
    searchLabel: "库内搜索",
    instructionsHint: "说明",
    queryHint: "查询"
  },
  plugin: {
    annotationsCouldNotFollow: "注解未能跟随重命名后的笔记；已保留它们的原始记录。",
    annotationsRestoreFailed: "无法恢复排队中的注解。",
    annotationNoteGone: "注解所属的笔记已不存在，未发送这些注解。",
    annotationSaveFailed: "无法把注解保存到插件数据。",
    commandsFailed: "Pi Agent：刷新 Pi 命令失败",
    contextBuilderUnavailable: "Pi 上下文构建器不可用。",
    errorPrefix: "错误：",
    historyBackupFailed: "Pi Agent：无法写入会话历史备份（data.json 已保存）。",
    historySaveFailed: "Pi Agent：无法保存会话历史",
    modelCatalogFailed: "Pi Agent：刷新模型目录失败",
    modelServiceNotReady: "Pi 模型服务尚未就绪。",
    runnerUnavailable: "Pi 运行器不可用。",
    servicesUnavailable: "Pi 服务不可用。",
    sessionCloneFailed: "Pi Agent：无法命名克隆的 Pi 会话",
    sessionDeleteFailed: "Pi Agent：无法删除本地 Pi 会话",
    sessionRenameFailed: "Pi Agent：无法重命名 Pi 会话",
    threadGone: "会话已不存在。",
    warningPrefix: "警告：",
    commandsLoaded: (count) => `已加载 ${count} 个 Pi 命令。`,
    couldNotOpenView: "无法打开 Pi 视图。",
    desktopOnly: "Pi Agent 仅支持桌面端。",
    historyRecovered: "Pi Agent 已从本地备份恢复会话历史。",
    noAnnotationsToSend: "该笔记没有可发送的注解。",
    openAgent: (name) => `打开 ${name}`,
    commandOpenChat: "打开智能体会话",
    commandToggleAnnotations: "为当前笔记添加或切换注解",
    commandAskCurrentNote: "询问当前笔记",
    commandResearchCurrentNote: "围绕当前笔记调研",
    commandSuggestFrontmatter: "为当前笔记建议 frontmatter",
    commandDraftBase: "根据当前笔记上下文草拟 Base",
    openMarkdownFirst: "请先打开一篇 Markdown 笔记。",
    settingsSaveFailed: (detail) => `Pi Agent：无法保存设置：${detail}`,
    cliAvailable: (version) => `Pi CLI 可用：${version}`,
    modelsLoaded: (count, model) => `已加载 ${count} 个 Pi 模型；默认 ${model}。`
  },
  history: {
    invalidBackup: "会话历史备份无效。",
    invalidMessage: "消息数据无效。",
    invalidThread: "会话数据无效。",
    pluginDirectoryUnavailable: "插件目录不可用。",
    unsafeFolder: "不安全的会话历史目录。",
    unsupportedSchema: "不支持的会话数据格式。"
  },
  picker: {
    custom: "自定义",
    noModelsReturned: "Pi 未返回任何模型。",
    piDefault: "Pi 默认"
  }
};
