import type {} from "../ui/PiAgentView.mjs";

declare module "../ui/PiAgentView.mjs" {
  interface PiAgentView {
    activeWindow?: any;
    activityItemEl?: any;
    activityDetailsEl?: any;
    activityLabelEl?: any;
    liveThinkingDetailsEl?: any;
    liveThinkingTextEl?: any;
    liveThinkingSetExpanded?: (expanded: boolean) => void;
    renderMessages(): void;
    restoreMessagesScroll(messagesEl: any, stickToBottom: boolean, previousScrollTop: number): void;
    renderEmptyState(): void;
    renderMessage(message: any, index: number): void;
    renderToolErrors(container: any, errors: any): void;
    renderThinkingDisclosure(...args: any[]): any;
    handleMessageLinkClick(event: any): boolean;
    renderPlainMessageContent(container: any, content: string): any;
    unloadMessageRenderComponents(): void;
    renderStreamingAssistantMessage(): void;
    renderStreamingAnswer(): void;
    renderStreamingThinking(): void;
    scheduleStreamingRender(): void;
    flushStreamingRender(): void;
    clearStreamingRenderTimer(): void;
    renderActivityMessage(): void;
    renderRoleLabel(parent: any, role: string, message?: any, index?: number): void;
    setActivity(text: string, kind: string, detail?: string): void;
    applyActivity(text: string, kind: string, detail?: string, stickyUntil?: number): void;
    queuePendingActivity(text: string, kind: string, detail?: string): void;
    schedulePendingActivity(): void;
    clearPendingActivityTimer(): void;
    flushPendingActivity(): void;
    updateActivityDom(): boolean;
    captureContextUsage(event: any): void;
    getContextUsageForTokens(tokenUsage: any): any;
    handleRunEvent(event: any): void;
    normalizeRunEventType(type: string): string;
    trackActiveTool(event: any): void;
    untrackActiveTool(event: any): void;
    formatActiveToolStatus(): { label: string; kind: string; detail: string };
    showThreadList(): void;
    renderThreadList(): void;
    renderThreadListRow(listEl: any, thread: any, isCurrent: boolean): void;
    deleteChats(): Promise<void>;
    showThreadRowMenu(event: any, thread: any, isCurrent: boolean, titleEl: any): void;
    startThreadListRename(thread: any, titleEl: any): void;
    toggleThreadFavorite(thread: any): void;
    deleteThreadFromList(thread: any): Promise<void>;
    formatThreadMeta(thread: any, isCurrent: boolean): string;
    countSessionEntries(nodes: any[]): number;
    formatThreadDate(value: any): string;
    enqueuePrompt(...args: any[]): void;
    runNextQueuedPrompt(): void;
    removeQueuedPrompt(id: string): void;
    retrieveQueuedPrompt(id: string): void;
    steerQueuedPrompt(id: string): Promise<void>;
    renderPromptQueue(): void;
    classifyVaultLinkTarget(value: string): any;
    openVaultLink(value: string, newLeaf?: boolean): Promise<void>;
    parseVaultLinkTarget(value: string): any;
    formatVaultLinkTarget(target: any): string;
    getLinkLabel(value: string): string;
    getLinkSourcePath(): string;
    revealLine(leaf: any, line: any): any;
    openVaultPath(value: string, newLeaf?: string): Promise<void>;
  }
}
